language: python
python:
- "2.7"
install: "pip install -r requirements.txt"
before_script:
- autopep8 -ir *
- flake8 --max-complexity=18 --exclude=*.txt,*.md --max-line-length=200 *
script:
- cd UnitTest
- python Test_Tenis.py
- coverage run --branch Test_Tenis.py
- coverage report -m
